Update autoconf + perl/package.py in sdsc pkg repo
Unfortunately, autoconf@2.7x is currently failing to build with
oneapi@2023.2.4 [1], which is severly limiting the number of packages
that can be built and tested with oneapi@2023.2.4 within exp/gpu/dev. No
recent reporting of this problem was found online. We will likely need to
revisit on the next build and deployment test.

[1]

==> Installing autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m [12/14]
==> No binary for autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/43/431075ad0bf529ef13cb41e9042c542381103e80015686222b8a9d4abef42a1c.tar.gz
==> Ran patch() for autoconf
==> autoconf: Executing phase: 'autoreconf'
==> autoconf: Executing phase: 'configure'
==> autoconf: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1' 'V=1'

6 errors found in build log:
     72      echo 'm4_define([m4_PACKAGE_URL],       [https://www.gnu.org/softw
           are/autoconf/])' && \
     73      echo 'm4_define([m4_PACKAGE_YEAR],      [2021])'; \
     74    } > lib/m4sugar/version.m4-t
     75    mv lib/m4sugar/version.m4-t lib/m4sugar/version.m4
     76    autom4te_perllibdir='/scratch/mkandes/job_35906665/spack-stage/spack
           -stage/spack-stage-autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m/sp
           ack-src'/lib AUTOM4TE_CFG='lib/autom4te.cfg'         bin/autom4te -B
            ''lib -B '/scratch/mkandes/job_35906665/spack-stage/spack-stage/spa
           ck-stage-autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m/spack-src'/l
           ib         --language M4sh --cache '' \
     77      --melt /scratch/mkandes/job_35906665/spack-stage/spack-stage/spack
           -stage-autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m/spack-src/bin/
           autoconf.as -o bin/autoconf.in
  >> 78    /scratch/mkandes/job_35906665/spack-stage/spack-stage/spack-stage-au
           toconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m/spack-src/bin/autoconf.
           as:23: error: m4_divert_pop(GROW): diversion mismatch:
  >> 79    /scratch/mkandes/job_35906665/spack-stage/spack-stage/spack-stage-au
           toconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m/spack-src/bin/autoconf.
           as:1: m4_divert: BODY
  >> 80    /scratch/mkandes/job_35906665/spack-stage/spack-stage/spack-stage-au
           toconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m/spack-src/bin/autoconf.
           as:23: the top level
  >> 81    autom4te: error: /home/mkandes/software/spack/repos/sdsc/gpu/opt/spa
           ck/linux-rocky8-cascadelake/oneapi-2023.2.4/m4-1.4.19-vid4vmz4zsszts
           ltxajnwnyz7rh6kzxj/bin/m4 failed with exit status: 1
  >> 82    make[1]: *** [Makefile:2128: bin/autoconf.in] Error 1
     83    make[1]: Leaving directory '/scratch/mkandes/job_35906665/spack-stag
           e/spack-stage/spack-stage-autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kc
           vz3m/spack-src/spack-build'
  >> 84    make: *** [Makefile:928: all] Error 2

See build log for details:
  /scratch/mkandes/job_35906665/spack-stage/spack-stage/spack-stage-autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m/spack-build-out.txt

==> Warning: Skipping build of libxc-6.2.2-ny75rtwhgibe57a2lelkxn6id2wyre5s since autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m failed
==> Warning: Skipping build of automake-1.16.5-kz3lem3omyvqix5txuw4zykk223yghrh since autoconf-2.71-4a5izoxcpmoglgw3ovsvvcd3f6kcvz3m failed
==> Error: Terminating after first install failure: ProcessError: Command exited with status 2:
    'make' '-j1' 'V=1'
real 11.92
user 9.19
sys 0.70
ERROR: spack install failed.