Add libxc@6.2.2 % gcc@11.8.0 +cuda@11.8.0 cuda_arch=70,80 to exp/gpu/dev
Note, however, the build still fails [1]. I do not recall if this is the
same issue observed for libxc@6.2.2 % gcc@13.3.0 +cuda@12.6.3
cuda_arch=70,80,90. We'll have to cross-check when time permits and,
hopefully, resolve the problem.

[1]

==> Installing libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5 [18/18]
==> No binary for libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/3b/3b0523924579cf494cafc6fea92945257f35692b004217d3dfd3ea7ca780e8dc.tar.gz
==> No patches needed for libxc
==> libxc: Executing phase: 'autoreconf'
==> libxc: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/scratch/mkandes/job_37284723/spack-stage/spack-stage/spack-stage-libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-11.5.0/libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5' '--disable-shared' '--enable-cuda'

13 errors found in build log:
     21    libtoolize: copying file 'm4/lt~obsolete.m4'
     22    autoreconf: configure.ac: not using Intltool
     23    autoreconf: configure.ac: not using Gtkdoc
     24    autoreconf: running: aclocal -I /home/mkandes/software/spack/repos/s
           dsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-11.5.0/libtool-2.4.7-
           djbimiuo63lu35nmt5sit4ltz5volvmf/share/aclocal --force -I m4
     25    autoreconf: running: /home/mkandes/software/spack/repos/sdsc/gpu/opt
           /spack/linux-rocky8-cascadelake/gcc-11.5.0/autoconf-2.72-vgwz4bgj4kq
           7txkgwa4xnw6jstvf5zw2/bin/autoconf --include=/home/mkandes/software/
           spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-11.5.0/l
           ibtool-2.4.7-djbimiuo63lu35nmt5sit4ltz5volvmf/share/aclocal --force
     26    configure.ac:148: warning: The macro 'AC_HEADER_STDC' is obsolete.
  >> 27    configure.ac:148: You should run autoupdate.
  >> 28    /scratch/mkandes/job_37284551/spack-stage/spack-stage/spack-stage-au
           toconf-2.72-vgwz4bgj4kq7txkgwa4xnw6jstvf5zw2/spack-src/lib/autoconf/
           headers.m4:663: AC_HEADER_STDC is expanded from...
  >> 29    configure.ac:148: the top level
     30    autoreconf: running: /home/mkandes/software/spack/repos/sdsc/gpu/opt
           /spack/linux-rocky8-cascadelake/gcc-11.5.0/autoconf-2.72-vgwz4bgj4kq
           7txkgwa4xnw6jstvf5zw2/bin/autoheader --include=/home/mkandes/softwar
           e/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-11.5.0
           /libtool-2.4.7-djbimiuo63lu35nmt5sit4ltz5volvmf/share/aclocal --forc
           e
     31    autoreconf: running: automake --add-missing --copy --force-missing
  >> 32    configure.ac:18: installing './compile'
  >> 33    configure.ac:123: installing './config.guess'
  >> 34    configure.ac:123: installing './config.sub'
  >> 35    configure.ac:12: installing './install-sh'
  >> 36    configure.ac:12: installing './missing'
     37    src/Makefile.am:179: warning: subst xc_f.lo,,$(firstword $(am_libxcf
           03_la_OBJECTS: non-POSIX variable name
  >> 38    src/Makefile.am:179: (probably a GNU make extension)
     39    src/Makefile.am:186: warning: subst libxcf03.lo,,$(firstword $(libxc
           f03_la_OBJECTS: non-POSIX variable name
  >> 40    src/Makefile.am:186: (probably a GNU make extension)
     41    src/Makefile.am:196: warning: subst libxcf90.lo,,$(firstword $(nodis
           t_libxcf90_la_OBJECTS: non-POSIX variable name
  >> 42    src/Makefile.am:196: (probably a GNU make extension)
     43    src/Makefile.am: installing './depcomp'
     44    parallel-tests: installing './test-driver'
     45    autoreconf: './install-sh' is updated
     46    autoreconf: './config.sub' is updated
     47    autoreconf: './config.guess' is updated
     48    autoreconf: Leaving directory '.'

     ...

     59    checking for gawk... gawk
     60    checking whether make sets $(MAKE)... yes
     61    checking whether make supports nested variables... yes
     62    checking whether make supports the include directive... yes (GNU sty
           le)
     63    checking for gcc... /home/mkandes/software/spack/repos/sdsc/gpu/opt/
           spack/linux-rocky8-cascadelake/gcc-11.5.0/cuda-11.8.0-4lftsdgfjghuuq
           qgily6cbbgfoafmff7/bin/nvcc -x cu -ccbin /home/mkandes/software/spac
           k/repos/sdsc/gpu/lib/spack/env/gcc/gcc
     64    checking whether the C compiler works... no
  >> 65    configure: error: in '/scratch/mkandes/job_37284723/spack-stage/spac
           k-stage/spack-stage-libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5/spa
           ck-src':
  >> 66    configure: error: C compiler cannot create executables
     67    See 'config.log' for more details

See build log for details:
  /scratch/mkandes/job_37284723/spack-stage/spack-stage/spack-stage-libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5/spack-build-out.txt

==> Error: Terminating after first install failure: ProcessError: Command exited with status 77:
    '/scratch/mkandes/job_37284723/spack-stage/spack-stage/spack-stage-libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-11.5.0/libxc-6.2.2-43jlyrrfe2yyazew4j2uhfjkwrzp3py5' '--disable-shared' '--enable-cuda'
real 139.44
user 13.31
sys 1.58
ERROR: spack install failed.