Move all AMD packages from sdsc package repo to limbo
Created a 'limbo' directory in the sdsc package repository and moved all
AMD packages into it. Initial spack spec/install tests with this
deployment branch were failing due to what seems like a conflict with
these AMD packages on initialization of the concretizer. e.g.,

  ==> Error: cannot import name 'LibflameBase'
  ==> Error: cannot import name 'FFTwBase'

Once the AMD packages were removed from var/spack/repos/sdsc/packages
and placed in var/spack/repos/sdsc/limbo, the conflicts were resolved.