Add nccl@2.23.4 % oneapi@2023.2.4 ^cuda@12.6.3 to exp/gpu/dev
Note, however, it looks like NCCL is not compatible with the Intel ICX
compiler at this time [1].

[1]

==> Installing nccl-2.23.4-1-fxwhw6olxfoqdlppyh5h75bq25crrezi [8/8]
==> No binary for nccl-2.23.4-1-fxwhw6olxfoqdlppyh5h75bq25crrezi found: installing from source
==> Using cached archive: /home/mkandes/software/spack/repos/sdsc/gpu/var/spack/cache/_source-cache/archive/6b/6b946b70a9d2d01871842cbd15ec56488d358abe9a0f3767e372fddc3e241ba7.tar.gz
==> No patches needed for nccl
==> nccl: Executing phase: 'edit'
==> nccl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10' 'CUDA_HOME=/home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/oneapi-2023.2.4/cuda-12.6.3-ep5xobmvyyhm2lpuadd34ykscoctcsvn' 'NVCC_GENCODE=--generate-code arch=compute_70,code=sm_70 --generate-code arch=compute_70,code=compute_70 --generate-code arch=compute_80,code=sm_80 --generate-code arch=compute_80,code=compute_80 --generate-code arch=compute_90,code=sm_90 --generate-code arch=compute_90,code=compute_90'

25 errors found in build log:
     683    NVCC_GENCODE is --generate-code arch=compute_70,code=sm_70 --genera
            te-code arch=compute_70,code=compute_70 --generate-code arch=comput
            e_80,code=sm_80 --generate-code arch=compute_80,code=compute_80 --g
            enerate-code arch=compute_90,code=sm_90 --generate-code arch=comput
            e_90,code=compute_90
     684    Dependencies    src/device/common.cu
     685    Dependencies    src/device/onerank.cu
     686    Dependencies    build/obj/device/gensrc/all_gather.cu
     687    In file included from <built-in>:1:
     688    In file included from /home/mkandes/software/spack/repos/sdsc/gpu/o
            pt/spack/linux-rocky8-cascadelake/oneapi-2023.2.4/cuda-12.6.3-ep5xo
            bmvyyhm2lpuadd34ykscoctcsvn/bin/../targets/x86_64-linux/include/cud
            a_runtime.h:82:
  >> 689    /home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-
            cascadelake/oneapi-2023.2.4/cuda-12.6.3-ep5xobmvyyhm2lpuadd34ykscoc
            tcsvn/bin/../targets/x86_64-linux/include/crt/host_config.h:124:2:
            error: -- unsupported Intel ICX compiler! The nvcc flag '-allow-uns
            upported-compiler' can be used to override this version check; howe
            ver, using an unsupported host compiler may cause compilation failu
            re or incorrect run time execution. Use at your own risk.
     690    #error -- unsupported Intel ICX compiler! The nvcc flag '-allow-uns
            upported-compiler' can be used to override this version check; howe
            ver, using an unsupported host compiler may cause compilation failu
            re or incorrect run time execution. Use at your own risk.
...