Set libarchive@3.5.3 as preferred=True; tmp fix for elfutils build
During the last build test of the core packages for exp/0.21.2/cpu/dev,
it was found that gdb@14.2 failed to build and install due to elfutils
failure to find libarchive during configuration [1]. This issue is known,
having been reported to the Spack project a few different times over the
past year or so [2]. Unfortunately, it is unclear if the issue has been
resolved in the latest versions of elfutils in Spack. I was not able to
resolve the issue either, except by downgrading to libarchive@3.5.3 as
the preferred version in our custom sdsc package for libarchive. This is
a temporary fix as this version may be the subject of a number of known
CVEs [3] [4] [5]. Note, however, this version of libarchive is newer
than the one available from the operating system on Expanse (Rocky 8.9).
Whether or not this version has been patched for the known CVEs is not
clear at this time.

[1]

==> Installing elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f [36/37]
==> No binary for elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f found: installing from source
==> Using cached archive: /home/mkandes/software/spack/repos/sdsc/spack/var/spack/cache/_source-cache/archive/df/df76db71366d1d708365fc7a6c60ca48398f14367eb2b8954efc8897147ad871.tar.bz2
==> Ran patch() for elfutils
==> elfutils: Executing phase: 'autoreconf'
==> elfutils: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/scratch/mkandes/job_34232782/spack-stage/spack-stage/spack-stage-elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f' '--with-bzlib=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/bzip2-1.0.8-lpkmsaf5ev2hvyubj3pbx37f2exobz62' '--with-lzma=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/xz-5.4.1-z6sauvemupza4gcfn7p6h6ezjqo3zonj' '--with-zlib=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/zlib-ng-2.1.4-f3aqwo6ho6rpaff6b5d5wvzse2bdr2tx' '--program-prefix='"'"'eu-'"'"'' '--with-zstd=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/zstd-1.5.5-a6unagkyhwsudbez7awhldqgr4r6vw2y' '--with-libiconv-prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/libiconv-1.17-z3hw4u6adyqv2fxp4xn6kxf4ud7uocjj' '--with-libintl-prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gettext-0.22.3-qmakjn5k6dj7pz7z5yalvfn43i7khroy' '--enable-debuginfod' '--enable-libdebuginfod'

1 error found in build log:
     143    checking for pkg-config... (cached) /home/mkandes/software/spack/re
            pos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/pkgconf-1.9.5-v
            xnd4ve4dumh44ahgmkqa7cwkfyoovwl/bin/pkg-config
     144    checking pkg-config is at least version 0.9.0... yes
     145    checking for libmicrohttpd >= 0.9.33... yes
     146    checking for libmicrohttpd < 0.9.51... yes
     147    checking for sqlite3 >= 3.7.17... yes
     148    checking for libarchive >= 3.1.2... no
  >> 149    configure: error: dependencies not found, use --disable-debuginfod
            to disable.

See build log for details:
  /scratch/mkandes/job_34232782/spack-stage/spack-stage/spack-stage-elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f/spack-build-out.txt

==> Warning: Skipping build of gdb-14.2-n6mwlmmhbazxgbuqay36tezvdhfy4svx since elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f failed
==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    '/scratch/mkandes/job_34232782/spack-stage/spack-stage/spack-stage-elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/elfutils-0.191-wfcoioeldckfxnwas5c3krmszerhhd5f' '--with-bzlib=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/bzip2-1.0.8-lpkmsaf5ev2hvyubj3pbx37f2exobz62' '--with-lzma=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/xz-5.4.1-z6sauvemupza4gcfn7p6h6ezjqo3zonj' '--with-zlib=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/zlib-ng-2.1.4-f3aqwo6ho6rpaff6b5d5wvzse2bdr2tx' '--program-prefix='"'"'eu-'"'"'' '--with-zstd=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/zstd-1.5.5-a6unagkyhwsudbez7awhldqgr4r6vw2y' '--with-libiconv-prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/libiconv-1.17-z3hw4u6adyqv2fxp4xn6kxf4ud7uocjj' '--with-libintl-prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gettext-0.22.3-qmakjn5k6dj7pz7z5yalvfn43i7khroy' '--enable-debuginfod' '--enable-libdebuginfod'
real 23.10
user 19.04
sys 2.12
ERROR: spack install failed.
[mkandes@login01 specs]$

[2] https://github.com/spack/spack/issues/36710
[3] https://github.com/advisories/GHSA-g5xc-jv8h-2232
[4] https://github.com/advisories/GHSA-2jc9-36w4-pmqw
[5] https://github.com/advisories/GHSA-gpgf-w78r-4pvj