Update mvapich2@2.3.7-2 % gcc@13.3.0 to ~cuda for exp/gpu/dev
Unfortunately, the mvapich2 still fails to build because OMB cannot find
the CUDA library [1]. It would be nice if there was a variant to disable
the build of OMB within the mvapich2 package.py --- or if OSU would
simply fix this long-standing issue.

[1]

==> Applied patch /home/mkandes/software/spack/repos/sdsc/gpu/var/spack/repos/sdsc/packages/mvapich2/mpir_attr_delete_list_segfault.patch
==> mvapich2: Executing phase: 'autoreconf'
==> mvapich2: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/scratch/mkandes/job_37136018/spack-stage/spack-stage/spack-stage-mvapich2-2.3.7-2-cqmjqqmxyeudpgdsrjcghtdetgropner/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-13.3.0/mvapich2-2.3.7-2-cqmjqqmxyeudpgdsrjcghtdetgropner' '--enable-shared' '--enable-romio' '--disable-silent-rules' '--disable-new-dtags' '--enable-fortran=all' '--enable-threads=multiple' '--with-ch3-rank-bits=32' '--enable-wrapper-rpath=yes' '--disable-alloca' '--enable-fast=all' '--enable-cuda' '--with-cuda=/home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-13.3.0/cuda-12.6.3-guub3z6c6k7zgb3qv3vdngxr6zu5mhzy' '--disable-opencl' '--disable-gl' '--disable-nvml' '--enable-registration-cache' '--with-pmi=pmi2' '--with-pm=slurm' '--with-slurm=/cm/shared/apps/slurm/current' '--with-device=ch3:mrail' '--with-rdma=gen2' '--disable-mcast' '--with-file-system=lustre'

2 errors found in build log:
     575    checking for inline... inline
     576    checking for getpagesize... yes
     577    checking for gettimeofday... yes
     578    checking for memset... yes
     579    checking for sqrt... yes
     580    checking for library containing cuPointerGetAttribute... no
  >> 581    configure: error: cannot link with -lcuda
  >> 582    configure: error: OMB configure failed

See build log for details:
  /scratch/mkandes/job_37136018/spack-stage/spack-stage/spack-stage-mvapich2-2.3.7-2-cqmjqqmxyeudpgdsrjcghtdetgropner/spack-build-out.txt

==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    '/scratch/mkandes/job_37136018/spack-stage/spack-stage/spack-stage-mvapich2-2.3.7-2-cqmjqqmxyeudpgdsrjcghtdetgropner/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-13.3.0/mvapich2-2.3.7-2-cqmjqqmxyeudpgdsrjcghtdetgropner' '--enable-shared' '--enable-romio' '--disable-silent-rules' '--disable-new-dtags' '--enable-fortran=all' '--enable-threads=multiple' '--with-ch3-rank-bits=32' '--enable-wrapper-rpath=yes' '--disable-alloca' '--enable-fast=all' '--enable-cuda' '--with-cuda=/home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky8-cascadelake/gcc-13.3.0/cuda-12.6.3-guub3z6c6k7zgb3qv3vdngxr6zu5mhzy' '--disable-opencl' '--disable-gl' '--disable-nvml' '--enable-registration-cache' '--with-pmi=pmi2' '--with-pm=slurm' '--with-slurm=/cm/shared/apps/slurm/current' '--with-device=ch3:mrail' '--with-rdma=gen2' '--disable-mcast' '--with-file-system=lustre'
real 46.24
user 34.95
sys 12.87
ERROR: spack install failed.