Add fftw@3.3.10 % gcc@10.2.0 +openmp to exp/0.17.3/cpu/b
Adding +openmp-enabled FFTW3 libraries to the production instances in an
attempt to satisfy a requirement for the latest versions of Quantum
Espresso, which appears to require a multithreaded FFTW-compatible
libary.  For example, this is the build error I'm currently running into
at the moment [1]. This is to resolve this ticket [2]. Unfortuantely, it
appears there is another issue with the fftw@3.3.10 build process when
enabling both +openmp and +mpi [3], at least with openmpi@4.1.3. I will
attempt to retry the +openmp deployment with mvapich2@2.3.7 next.

[1]

...
Scanning dependencies of target test_qe_fftx_fwinv_gpu
[  5%] Building Fortran object FFTXlib/tests/CMakeFiles/test_qe_fftx_fwinv_gpu.dir/test_fwinv_gpu.f90.o
[  5%] Linking Fortran executable ../bin/test_qe_fftx_fwinv_gpu.x
../src/libqe_fftx.so: undefined reference to `fftw_plan_with_nthreads'
../src/libqe_fftx.so: undefined reference to `fftw_init_threads'
collect2: error: ld returned 1 exit status
make[2]: *** [FFTXlib/tests/CMakeFiles/test_qe_fftx_fwinv_gpu.dir/build.make:99: FFTXlib/bin/test_qe_fftx_fwinv_gpu.x] Error 1
make[1]: *** [CMakeFiles/Makefile2:1306: FFTXlib/tests/CMakeFiles/test_qe_fftx_fwinv_gpu.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

[2] https://sdsc.zendesk.com/agent/tickets/37410

[3]

==> Ran patch() for fftw
==> fftw: Executing phase: 'autoreconf'
==> fftw: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '../configure' '--prefix=/cm/shared/apps/spack/0.17.3/cpu/b/opt/spack/linux-rocky8-zen2/gcc-10.2.0/fftw-3.3.10-3xf36y35ojmpkeaypk2ys6i3g23pgfft' '--enable-shared' '--enable-threads' '--enable-openmp' '--enable-mpi' '--enable-sse2' '--enable-avx' '--enable-avx2' '--disable-avx512' '--disable-avx-128-fma' '--disable-kcvi' '--disable-vsx' '--enable-fma'

1 error found in build log:
     84    checking for ranlib... (cached) ranlib
     85    checking for ocamlbuild... no
     86    checking for mpicc... /cm/shared/apps/spack/0.17.3/cpu/b/opt/spack/l
           inux-rocky8-zen2/gcc-10.2.0/openmpi-4.1.3-oq3qvsvt5mywjzy7xzrfeh6eeb
           iujvbm/bin/mpicc
     87    checking for MPI_Init... no
     88    checking for MPI_Init in -lmpi... no
     89    checking for MPI_Init in -lmpich... no
  >> 90    configure: error: could not find mpi library for --enable-mpi

See build log for details:
  /scratch/spack_cpu/job_33151837/spack-stage/spack-stage-fftw-3.3.10-3xf36y35ojmpkeaypk2ys6i3g23pgfft/spack-build-out.txt

==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    '../configure' '--prefix=/cm/shared/apps/spack/0.17.3/cpu/b/opt/spack/linux-rocky8-zen2/gcc-10.2.0/fftw-3.3.10-3xf36y35ojmpkeaypk2ys6i3g23pgfft' '--enable-shared' '--enable-threads' '--enable-openmp' '--enable-mpi' '--enable-sse2' '--enable-avx' '--enable-avx2' '--disable-avx512' '--disable-avx-128-fma' '--disable-kcvi' '--disable-vsx' '--enable-fma'