Update magma@2.8.0 % intel@2021.10.0 to magma@2.9.0 +cuda@12.6.3
Note, however, the build still fails [1].

[1]

101 errors found in build log:
     36     -- Found OpenMP_CXX: -qopenmp (found version "5.0")
     37     -- Found OpenMP_Fortran: -qopenmp (found version "5.0")
     38     -- Found OpenMP: TRUE (found version "5.0")
     39     -- Found OpenMP
     40     --     OpenMP_C_FLAGS   -qopenmp
     41     --     OpenMP_CXX_FLAGS -qopenmp
  >> 42     CMake Error at /home/mkandes/software/spack/repos/sdsc/gpu/opt/spac
            k/linux-rocky8-cascadelake/intel-2021.10.0/cmake-3.31.2-auzd5rhq5fe
            6jzf4su465lg7aulnhfly/share/cmake-3.31/Modules/CMakeDetermineCompil
            erId.cmake:865 (message):
     43       Compiling the CUDA compiler identification source file
     44       "CMakeCUDACompilerId.cu" failed.
     45
     46       Compiler:
     47       /home/mkandes/software/spack/repos/sdsc/gpu/opt/spack/linux-rocky
            8-cascadelake/intel-2021.10.0/cuda-12.6.3-frf6lej72dpsgmgxm3nsmuouz
            epayze2/bin/nvcc
     48

     ...

     196      icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is d
            eprecated
     197      and will be removed from product release in the second half of 20
            23.  The
     198      Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compi
            ler moving
     199      forward.  Please transition to use this compiler.  Use
     200      '-diag-disable=10441' to disable this message.
     201
  >> 202    /usr/include/stdlib.h(140): error: identifier "_Float32" is undefin
            ed
     203
     204        extern _Float32 strtof32(const char *__restrict__ __nptr, char
            **__restrict__ __endptr) throw()
     205               ^
     206
     207
     208
  >> 209    /usr/include/stdlib.h(146): error: identifier "_Float64" is undefin
            ed
     210
     211        extern _Float64 strtof64(const char *__restrict__ __nptr, char
            **__restrict__ __endptr) throw()
...