Fix mpfr dependency for latest versions of gdb in gdb/package.py
Previous test build of gdb@14.2 failed due to a missing mpfr dependency [1],
which was not in the gdb/package.py file, but is correctly in the current
develop version of the package.py in spack/spack upstream repo.

[1]

==> Installing gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t [38/38]
==> No binary for gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t found: installing from source
==> Using cached archive: /home/mkandes/software/spack/repos/sdsc/spack/var/spack/cache/_source-cache/archive/2d/2de5174762e959a5e529e20c20d88a04735469d8fffd98f61664e70b341dc47c.tar.gz
==> Applied patch /home/mkandes/software/spack/repos/sdsc/spack/var/spack/repos/sdsc/packages/gdb/gdb-libintl-11.patch
==> gdb: Executing phase: 'autoreconf'
==> gdb: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/scratch/mkandes/job_34156818/spack-stage/spack-stage/spack-stage-gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t' '--with-system-gdbinit=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t/etc/gdbinit' '--with-system-zlib' '--disable-lto' '--without-quad' '--disable-gold' '--disable-ld' '--disable-tui' '--with-debuginfod' '--with-zstd' '--with-gmp=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gmp-6.2.1-jtirhaj43irk5t5fdmqjvm3khmnb4g7o' '--with-python=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/python-3.11.9-77b2snck3zdse3uusv4mgio7seihpfi5/bin/python3.11' 'LDFLAGS=-L/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/python-3.11.9-77b2snck3zdse3uusv4mgio7seihpfi5/lib -lpython3.11'

1 error found in build log:
     32    checking for gdc... no
     33    checking whether the D compiler works... no
     34    checking how to compare bootstrapped objects... cmp --ignore-initial
           =16 $$f1 $$f2
     35    checking for objdir... .libs
     36    checking for the correct version of gmp.h... yes
     37    checking for the correct version of mpfr.h... no
  >> 38    configure: error: Building GDB requires GMP 4.2+, and MPFR 3.1.0+.
     39    Try the --with-gmp and/or --with-mpfr options to specify
     40    their locations.  If you obtained GMP and/or MPFR from a vendor
     41    distribution package, make sure that you have installed both the lib
           raries
     42    and the header files.  They may be located in separate packages.

See build log for details:
  /scratch/mkandes/job_34156818/spack-stage/spack-stage/spack-stage-gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t/spack-build-out.txt

==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    '/scratch/mkandes/job_34156818/spack-stage/spack-stage/spack-stage-gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t/spack-src/configure' '--prefix=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t' '--with-system-gdbinit=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gdb-14.2-igrah6yxl3e3jheknnpdmd3utieiuz3t/etc/gdbinit' '--with-system-zlib' '--disable-lto' '--without-quad' '--disable-gold' '--disable-ld' '--disable-tui' '--with-debuginfod' '--with-zstd' '--with-gmp=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/gmp-6.2.1-jtirhaj43irk5t5fdmqjvm3khmnb4g7o' '--with-python=/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/python-3.11.9-77b2snck3zdse3uusv4mgio7seihpfi5/bin/python3.11' 'LDFLAGS=-L/home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/python-3.11.9-77b2snck3zdse3uusv4mgio7seihpfi5/lib -lpython3.11'
real 23.47
user 17.84
sys 1.39
ERROR: spack install failed.