intel@19.1.3.304 compiler module hierarchy is lost at some point
During the test build of the expanse/0.17.2/cpu instance, it was found
that the mpi hierarchy for the intel@19.1.3.304 lmod modules is lost at
some point. The problem is triggered while building similar packages
with other compilers and mpi distributions. e.g., while building the
openmpi@4.1.3 % gcc@10.2.0 package dependency chain. The problem was
first noticed when name clashes error were thrown for intel@19.1.3.304
built packages upon refreshing the module tree [2]. We added the short
(7-digit) spack hash back to the module naming scheme in the modules.yaml
file to try and avoid triggering the problem and the name clash error.
While this change does avoid the name clash error for the modules, it
does not avoid the breakdown of the hierarchy [3]. We will ignore this
issue for now and revisit the problem again in the future --- which may
or may not be an unintended consquence of the changes made to spack in
v0.17.2 to 'fix handling of Intel compiler environment' [4].

[1]

Error: Name clashes detected in module files

[2]

spack module lmod refresh --delete-tree -y

[3]

[mkandes@login01 ~]$ module avail

-------------------------------- /home/mkandes/cm/shared/apps/spack/0.17.2/cpu/share/spack/lmod/linux-rocky8-x86_64/intel/19.1.3.304 --------------------------------
   arpack-ng/3.7.0/psbvisl          hypre/2.23.0/fyreqvp                 netcdf-fortran/4.5.3/fxj7ige              petsc/3.16.1/hex6qdp        (D)
   arpack-ng/3.8.0/7kl3u6w          hypre/2.23.0/ppz4cxn          (D)    netcdf-fortran/4.5.3/hplpk7y       (D)    slepc/3.16.0/b6ebr2b-cmplx
   cmake/3.21.4/z5sqlux             intel-mkl/2020.4.304/cvci4xh         netlib-lapack/3.9.1/vnxycyc               slepc/3.16.0/g5x5ep4        (D)
   eigen/3.4.0/fs7wd23              intel-mpi/2019.10.317/fccah6b (L)    netlib-scalapack/2.1.0/lmoicxr            sprng/5.0/rewep3f
   fftw/3.3.10/fgch5jv              ior/3.3.0/xktpv5e                    openblas/0.3.18/biju76m                   suite-sparse/5.10.1/yhhodzd
   fftw/3.3.10/2vadcn7     (D)      metis/5.1.0/in7vwo3                  openblas/0.3.18/5dqeuya-omp        (D)    superlu-dist/7.1.1/guxt5tq
   gsl/2.7/metv25i                  mpip/3.5/tzs66xy                     osu-micro-benchmarks/5.7.1/mkoub6d        superlu/5.3.0/wzjr2ce
   hdf5/1.10.7/zyge4wv              netcdf-c/4.8.1/qcahg75               papi/6.0.0.1/u7q3xry                      valgrind/3.17.0/awzroms
   hdf5/1.10.7/2xjhpy6     (D)      netcdf-c/4.8.1/5lcec4c        (D)    parallel-netcdf/1.12.2/evjdwjg            valgrind/3.17.0/hc3px4a     (D)
   hpl/2.3/imwygnl                  netcdf-cxx4/4.3.1/f4v3c4d            parmetis/4.0.3/g5uj4eu
   hpl/2.3/6hjpz5h-omp     (L,D)    netcdf-cxx4/4.3.1/3hvr5ps     (D)    petsc/3.16.1/gvy36hc-cmplx

-------------------------------------- /home/mkandes/cm/shared/apps/spack/0.17.2/cpu/share/spack/lmod/linux-rocky8-x86_64/Core --------------------------------------
   anaconda3/2021.05/q4munrg             gcc/10.2.0/npcyll4              lmod/8.5.6/pn4xltl           rclone/1.56.2/mldjorr        xpmem/2.6.5-36/jnrkrz2
   aocc/3.2.0/io3s466                    git-lfs/2.11.0/kmruniy          mercurial/5.8/qmgrjvl        sratoolkit/2.10.9/rn4humf
   aria2/1.35.0/q32jtg2                  git/2.31.1/ldetm5y              parallel/20210922/sqru6rr    subversion/1.14.0/qpzq6zs
   entrezdirect/10.7.20190114/6pkkpx2    intel/19.1.3.304/6pv46so (L)    pigz/2.6/bgymyil             ucx/1.10.1/dcghxa2

[4]

https://github.com/spack/spack/releases/tag/v0.17.2