Add bcftools@1.10.2 % gcc@10.2.0 to expanse/0.15.4/cpu
Note, however, the installation failed with the following error:

  Error: Detected uninstalled dependencies for libpng: {'zlib'}
  Error: Cannot proceed with libpng: 1 uninstalled dependency: zlib

We'll attempt to rectify this issue on the next rebuild of the instance
and/or once we upgrade to Spack v0.17.X. This is why the package has not
yet been included within the dependency chain.