Modify perl-* package.py files to fix build system problems
It appears some perl packages in (at least) Spack v0.21.2 have a problem
with the build system transition the Spack developers have been preparing
for in the upcoming versions of Spack. For example, while installing
entrezdirect@22.6.20240924 as part of the new core packages of
exp/0.21.2/cpu/dev, I ran into this error [1], which may originate as
far back as Spack v0.19.x [2]. This commit implements the changes to fix
the problem as show here [3]. Hopefully this issue is resolved in the
upcoming versions of Spack and we don't have to implement this fix too
often with various perl-* package depenedencies in Spack v0.21.2.

[1]

[+] /home/mkandes/software/spack/repos/sdsc/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/perl-module-build-0.4232-ekdhjj2x7z3eyugbqwcl4ijtmglof55q
==> Installing perl-net-ssleay-1.85-2vlydashk3ui3nfuqcdafodgngqqxt2c [26/43]
==> No binary for perl-net-ssleay-1.85-2vlydashk3ui3nfuqcdafodgngqqxt2c found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/9d/9d8188b9fb1cae3bd791979c20554925d5e94a138d00414f1a6814549927b0c8.tar.gz
==> No patches needed for perl-net-ssleay
==> perl-net-ssleay: Executing phase: 'configure'
==> Error: AttributeError: 'Adapter' object has no attribute 'build_method'

The 'perl-net-ssleay' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/home/mkandes/software/spack/repos/sdsc/spack/lib/spack/spack/build_systems/perl.py:103, in fix_shebang:
        101    @spack.builder.run_after("configure")
        102    def fix_shebang(self):
  >>    103        if self.build_method == "Build.PL":
        104            pattern = "#!{0}".format(self.spec["perl"].command.path)
        105            repl = "#!/usr/bin/env perl"
        106            filter_file(pattern, repl, "Build", backup=False)

See build log for details:
  /scratch/mkandes/job_34138950/spack-stage/spack-stage/spack-stage-perl-net-ssleay-1.85-2vlydashk3ui3nfuqcdafodgngqqxt2c/spack-build-out.txt

==> Warning: Skipping build of perl-io-socket-ssl-2.052-aolmvdckds54fq35mqzzw3wzxo6k5szm since perl-net-ssleay-1.85-2vlydashk3ui3nfuqcdafodgngqqxt2c failed
==> Warning: Skipping build of perl-lwp-protocol-https-6.04-gcj6nhqgzrauyez5byqpzm5gxttvv63g since perl-io-socket-ssl-2.052-aolmvdckds54fq35mqzzw3wzxo6k5szm failed
==> Warning: Skipping build of entrezdirect-22.6.20240924-63kr45expjgtn5eilnojrq5vkos5q7ob since perl-lwp-protocol-https-6.04-gcj6nhqgzrauyez5byqpzm5gxttvv63g failed
==> Error: Terminating after first install failure: AttributeError: 'Adapter' object has no attribute 'build_method'

The 'perl-net-ssleay' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure
real 162.21
user 40.83
sys 14.08
ERROR: spack install failed.

[2] https://github.com/spack/spack/issues/41234
[3] https://github.com/spack/spack/pull/41396